
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS hackreactor;
DROP TABLE IF EXISTS francis;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE hackreactor (id INT AUTO_INCREMENT, cohort INT(3) DEFAULT 1, PRIMARY KEY(id));

CREATE TABLE francis (id INT AUTO_INCREMENT, lastname VARCHAR(10), alive TINYINT(1) DEFAULT 1, id_hackreactor INT NOT NULL REFERENCES hackreactor(id), PRIMARY KEY(id));

